# Generated by Django 5.1.4 on 2025-01-05 05:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blogpage_remove_jobpage_page_ptr_delete_jobindexpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('title', 1), ('text', 3), ('image', 6), ('link', 9), ('important_dates', 12), ('application_fee', 13), ('vacancy_details', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('text', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('button_text', 7), ('button_link', 8)]], {}), 10: ('wagtail.blocks.DateBlock', (), {'required': True}), 11: ('wagtail.blocks.TimeBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('date_label', 7), ('date', 10), ('time', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('category', 7), ('amount', 7)]], {}), 14: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('trade_name', 7), ('total_posts', 7), ('eligibility', 14)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
    ]
