# Generated by Django 5.1.4 on 2025-01-05 08:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_blogpage_author_alter_blogpage_content_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('organization', models.CharField(max_length=255)),
                ('advertisement_number', models.CharField(max_length=100)),
                ('post_title', models.CharField(max_length=255)),
                ('short_description', wagtail.fields.RichTextField(blank=True)),
                ('content', wagtail.fields.StreamField([('recruitment_header', 3), ('important_dates', 6), ('vacancy_details', 11), ('eligibility', 14), ('application_fee', 19), ('important_links', 21), ('how_to_apply', 24), ('additional_information', 26)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('post_name', 0), ('organization', 0), ('advertisement_number', 1), ('total_vacancies', 2)]], {}), 4: ('wagtail.blocks.DateBlock', (), {'required': True}), 5: ('wagtail.blocks.DateBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('application_start_date', 4), ('application_end_date', 4), ('fee_payment_deadline', 5), ('exam_date', 5), ('admit_card_date', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.IntegerBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('category_name', 7), ('number_of_posts', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('category', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('post_name', 7), ('category_distribution', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('minimum_age', 8), ('maximum_age', 8), ('educational_qualification', 12), ('age_relaxation', 13)]], {}), 15: ('wagtail.blocks.DecimalBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('category_name', 7), ('fee_amount', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('category_fee', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (7,), {}), 19: ('wagtail.blocks.StructBlock', [[('fee_categories', 17), ('payment_methods', 18)]], {}), 20: ('wagtail.blocks.URLBlock', (), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('apply_online_url', 20), ('notification_url', 20), ('official_website', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'How to Apply', 'required': True}), 23: ('wagtail.blocks.ListBlock', (12,), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('steps', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('text', 25)]], {'required': False})})),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Job Recruitment Post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
