# Generated by Django 5.1.4 on 2025-01-05 09:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpostpage_delete_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostpage',
            name='content',
            field=wagtail.fields.StreamField([('recruitment_header', 3), ('important_dates', 6), ('vacancy_details', 12), ('category_distribution', 16), ('eligibility', 19), ('application_fee', 23), ('important_links', 25), ('how_to_apply', 28), ('additional_information', 30)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('post_name', 0), ('organization', 0), ('advertisement_number', 1), ('total_vacancies', 2)]], {}), 4: ('wagtail.blocks.DateBlock', (), {'required': True}), 5: ('wagtail.blocks.DateBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('application_start_date', 4), ('application_end_date', 4), ('fee_payment_deadline', 5), ('exam_date', 5), ('admit_card_date', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.IntegerBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (7,), {}), 10: ('wagtail.blocks.StructBlock', [[('category_name', 7), ('number_of_posts', 8), ('eligibility', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('category', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('post_name', 7), ('category_distribution', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Category Wise Vacancy Details'}), 14: ('wagtail.blocks.StructBlock', [[('post_name', 7), ('post_code', 7), ('ur', 8), ('obc', 8), ('ews', 8), ('sc', 8), ('st', 8), ('total', 8)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('block_title', 13), ('categories', 15)]], {}), 17: ('wagtail.blocks.RichTextBlock', (), {}), 18: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 19: ('wagtail.blocks.StructBlock', [[('minimum_age', 8), ('maximum_age', 8), ('educational_qualification', 17), ('age_relaxation', 18)]], {}), 20: ('wagtail.blocks.DecimalBlock', (), {}), 21: ('wagtail.blocks.StructBlock', [[('category_name', 7), ('fee_amount', 20)]], {}), 22: ('wagtail.blocks.StreamBlock', [[('category_fee', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('fee_categories', 22), ('payment_methods', 9)]], {}), 24: ('wagtail.blocks.URLBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('apply_online_url', 24), ('notification_url', 24), ('official_website', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'How to Apply', 'required': True}), 27: ('wagtail.blocks.ListBlock', (17,), {}), 28: ('wagtail.blocks.StructBlock', [[('title', 26), ('steps', 27)]], {}), 29: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 30: ('wagtail.blocks.StructBlock', [[('text', 29)]], {'required': False})}),
        ),
    ]
