apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daftardost
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # Rule for hostname
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: daftardost
                port:
                  number: 80
    # Rule for IP-based access
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: daftardost
                port:
                  number: 80
