replicaCount: 1
image:
  repository: abhishekp084/daftardost
  pullPolicy: IfNotPresent
  tag: "12621393761"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
