apiVersion: v1 
kind: Service
metadata:
  name: daftardost
  labels:
    app: daftardost
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
      app: daftardost
  type: ClusterIP